/**
 * Cała treść sesji w jednym miejscu. README i panel są z tego generowane,
 * więc dopisanie projektu to edycja jednej tablicy tutaj.
 */

/** Maksymalna szerokość wiersza w znakach. Pilnowana przez generator. */
export const COLS = 78;

/** Wypis `neofetch` — pary etykieta/wartość. Trzeci element wyróżnia wiersz. */
export const NEOFETCH = [
  ["role", "AI Automation Engineer", true],
  ["builds", "voice agents · LLM pipelines · process automation", false],
  ["stack", "n8n · FastAPI · NestJS · PostgreSQL · Docker · k8s", false],
  ["ai", "OpenAI Realtime · Gemini · ElevenLabs · Deepgram", false],
  ["hardware", "AEROS — wearable ECG on nRF52840, ADS1292, BQ25185", false],
  ["studies", "Medical Informatics @ Wrocław Univ. of Science and Tech.", false],
  ["club", "KN BioAddMed — additive manufacturing for medicine", false],
  ["after-hours", "LoRA on FLUX / Stable Diffusion, Kohya_ss, RTX 4070", false],
  ["location", "Wrocław, Poland", false],
];

export const STACK = {
  llm: ["OpenAI Realtime", "Gemini", "Vertex AI"],
  speech: ["ElevenLabs", "Deepgram", "DeepL"],
  voice: ["Twilio ConversationRelay", "FreeSWITCH", "Asterisk", "SIP B2BUA"],
  rag: ["Supabase Vector Store"],
  backend: ["Python", "FastAPI", "NestJS", "Node.js", "PostgreSQL + RLS", "Redis", "Neo4j"],
  frontend: ["Next.js", "TypeScript", "Flutter"],
  automation: ["n8n", "MCP", "GoHighLevel", "Zapier"],
  infra: ["Docker", "Kubernetes", "nginx", "Linux", "CUDA"],
  embedded: ["nRF52840 Sense", "ADS1292", "BQ25185"],
};

/** Strona `man` — nagłówki sekcji rozpoznawane po tym, że nie są wcięte. */
export const MANPAGE = `ARCHITECTURE(7)      Miscellaneous Information Manual      ARCHITECTURE(7)

NAME
     architecture — the patterns I build with

MULTI-TENANCY
     PostgreSQL with row-level security. Tenant isolation is enforced by
     the database, not by application code, so a forgotten WHERE clause
     cannot leak another tenant's rows.

OFFLINE-FIRST SYNC
     Flutter with idempotent sync keyed on client_uuid. Retries never
     create duplicates, so the app stays usable with no network at all.

VOICE AGENTS
     Twilio ConversationRelay and SIP B2BUA on FreeSWITCH, with speech
     recognition and synthesis running inside the call loop.

RETRIEVAL
     Supabase Vector Store, with embeddings generated by Vertex AI.

STRUCTURED EXTRACTION
     Model output constrained by JSON Schema. The model has no way to
     hand back something the next step cannot parse.

EVENT-DRIVEN
     Webhooks and queues instead of polling.

NOTES
     Docker and nginx are in production. Scaling n8n across Docker Swarm
     and Kubernetes is a designed path, not a deployment yet.

Nikodem Jachec                  2026-08                  ARCHITECTURE(7)`;

/** Kolumna uprawnień niesie informację: drwx------ to repozytorium prywatne. */
export const PROJECTS = [
  {
    mode: "drwx------",
    name: "aeros/",
    vis: "private",
    body: `Wearable ECG recorder. An ADS1292 analog front-end captures the
electrode signal, an nRF52840 Sense Plus runs the device, and a
BQ25185 handles power and charging. The hardware side of what I
study on Medical Informatics.`,
  },
  {
    mode: "drwxr-xr-x",
    name: "smart-campus-pwr/",
    vis: "public",
    body: `Android app for students at Wrocław University of Science and
Technology — everyday campus business gathered in one place,
instead of bouncing between five separate university systems.`,
  },
  {
    mode: "drwx------",
    name: "neurodiet-ai/",
    vis: "private",
    body: `Flutter app that puts an LLM behind meal planning. It reads what
you actually eat and adapts, rather than handing you a static
calorie table.`,
  },
  {
    mode: "drwx------",
    name: "ai-doktor/",
    vis: "private",
    body: `Web-based medical assistant built on an LLM. It runs the initial
interview and turns loose symptoms into something structured.
Triage support, not a diagnosis.`,
  },
];

export const CONTACT = [
  ["email", "nikodem@automee.pl"],
  ["company", "automee.pl"],
  ["github", "github.com/NikodemJachec99"],
  ["studies", "medinf.pwr.edu.pl"],
  ["club", "github.com/BioAddMed"],
  ["location", "Wrocław, Poland"],
];

export const STATS_NOTE = `Public repositories only — the n8n, FastAPI and Twilio voice work
sits in private client repos.`;

/** Formatuje stack jako JSON z zawijaniem tablic, żeby zmieścić się w COLS. */
export function stackJson(cols = COLS) {
  const keys = Object.keys(STACK);
  const pad = Math.max(...keys.map((k) => k.length));
  const out = ["{"];

  keys.forEach((k, i) => {
    const head = `  "${k}":${" ".repeat(pad - k.length + 1)}[`;
    const indent = " ".repeat(head.length);
    const tail = i < keys.length - 1 ? "]," : "]";

    let line = head;
    let first = true;
    STACK[k].forEach((v, j) => {
      const item = `"${v}"` + (j < STACK[k].length - 1 ? ", " : "");
      if (!first && line.length + item.length > cols) {
        out.push(line.replace(/ +$/, ""));
        line = indent;
      }
      line += item;
      first = false;
    });
    out.push(line.replace(/, $/, ",").replace(/ +$/, "") + tail);
  });

  out.push("}");
  return out.join("\n");
}
